version: 2

build:
  os: "ubuntu-24.04"
  tools:
    python: "3.8"

python:
   install:
      - method: pip
        path: .
        extra_requirements:
          - doc

sphinx:
  configuration: docs/sphinx/source/conf.py